server:
  context-path: /cmfz
  port: 9898
  jsp-servlet:
    init-parameters:
      development: true
spring:
  http:
    encoding:
      charset: utf-8
      force: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cmfz
    username: root
    password: 123
  mvc:
    view:
      prefix: /
      suffix: .jsp
mybatis:
  type-aliases-package: com.wucong.cmfz.entity